// Generated by scripts/export_openapi.py. Do not edit.
//
// The digest of the OpenAPI document this bundle's API client was generated from. A
// running server reports the digest of the contract it actually serves on
// /api/version; when the two differ, this bundle is talking to a server it was not
// built against, and src/components/VersionSkew.tsx says so.
export const BUNDLE_API_DIGEST = "d87c2aa099baf3081de33b5348f0dd00dc0c06cbc23d43d9faed0cd776babdee";
