// Generated by scripts/export_openapi.py. Do not edit.
//
// The digest of the OpenAPI document this bundle's API client was generated from. A
// running server reports the digest of the contract it actually serves on
// /api/version; when the two differ, this bundle is talking to a server it was not
// built against, and src/components/VersionSkew.tsx says so.
export const BUNDLE_API_DIGEST = "06de872a72a2a81663065220c218f4fa11c1d7cb510b3134c639f0aa51d4622b";
