"""Export the exact FastAPI OpenAPI document without starting a server.

Two artefacts come out of one render, because they must never disagree: the document
the TypeScript client is generated from, and the digest of that document compiled into
the bundle so a running app can tell whether it is talking to the server it was built
against. See `agentjobs.api.contract`.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Optional

from agentjobs.api.contract import canonical_document, contract_digest
from agentjobs.api.main import app

DIGEST_MODULE_HEADER = """\
// Generated by scripts/export_openapi.py. Do not edit.
//
// The digest of the OpenAPI document this bundle's API client was generated from. A
// running server reports the digest of the contract it actually serves on
// /api/version; when the two differ, this bundle is talking to a server it was not
// built against, and src/components/VersionSkew.tsx says so.
"""


def render_openapi() -> str:
    """Return a deterministic representation of the document served at /openapi.json."""
    return canonical_document(app.openapi())


def render_digest_module() -> str:
    """Return the TypeScript module that stamps the contract digest into the bundle."""
    digest = contract_digest(app.openapi())
    return f'{DIGEST_MODULE_HEADER}export const BUNDLE_API_DIGEST = "{digest}";\n'


def default_digest_module(output: Path) -> Path:
    """Where the digest module goes, given where the OpenAPI document is written.

    Derived rather than configured. The two artefacts are one render, and letting a
    caller point them at unrelated places invites exactly the drift this exists to
    detect.
    """
    return output.parent / "src" / "api" / "apiDigest.ts"


def _check(path: Path, expected: str) -> bool:
    """Whether the file on disk is what this render produces, saying so either way."""
    actual = path.read_text(encoding="utf-8") if path.is_file() else None
    if actual != expected:
        print(f"{path} is stale; run `npm run generate:api` from frontend/.")
        return False
    print(f"{path} matches the FastAPI OpenAPI document.")
    return True


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="Path to the checked-in OpenAPI JSON file")
    parser.add_argument(
        "--digest-module",
        type=Path,
        default=None,
        help="Where the contract digest module goes (default: <output dir>/src/api/apiDigest.ts)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when a checked-in artefact is stale",
    )
    args = parser.parse_args(argv)
    digest_module: Path = args.digest_module or default_digest_module(args.output)
    expected_document = render_openapi()
    expected_digest = render_digest_module()

    if args.check:
        document_ok = _check(args.output, expected_document)
        digest_ok = _check(digest_module, expected_digest)
        return 0 if document_ok and digest_ok else 1

    args.output.write_text(expected_document, encoding="utf-8", newline="\n")
    print(f"Wrote {args.output} from the FastAPI OpenAPI document.")
    digest_module.parent.mkdir(parents=True, exist_ok=True)
    digest_module.write_text(expected_digest, encoding="utf-8", newline="\n")
    print(f"Wrote {digest_module} with the contract digest.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
