#!/usr/bin/env bash
# Regenerate every artifact derived from the LinkML schemas.
#
# The two files in schema/ are the source of truth for schema *shape*; everything
# this script writes is generated and should never be hand-edited. Run it after
# any change to schema/agentjobs-v1.yaml or schema/agentjobs-v2.yaml.
#
# Usage:  bash scripts/regen-schema-docs.sh
set -euo pipefail

cd "$(dirname "$0")/.."

V1=schema/agentjobs-v1.yaml
V2=schema/agentjobs-v2.yaml
OUT=schema/generated

mkdir -p "$OUT"

echo "== JSON Schema =="
poetry run gen-json-schema "$V1" > "$OUT/agentjobs-v1.schema.json"
poetry run gen-json-schema "$V2" > "$OUT/agentjobs-v2.schema.json"

echo "== Entity diagrams (mermaid) =="
poetry run gen-erdiagram "$V1" > "$OUT/agentjobs-v1.er.mmd"
poetry run gen-erdiagram "$V2" > "$OUT/agentjobs-v2.er.mmd"

echo "== Pydantic preview (v2 -- the input to task-050, not yet wired in) =="
poetry run gen-pydantic "$V2" > "$OUT/models_v2_preview.py"

echo "== Reference docs =="
# --subfolder-type-separation is REQUIRED on Windows, not cosmetic. Without it
# gen-doc writes a page per class *and* per slot into one flat directory, so
# names that differ only by case -- Ball.md (enum) vs ball.md (slot), Task.md vs
# task.md, Spec.md vs spec.md -- collide on a case-insensitive filesystem and the
# slot page silently overwrites the class/enum page. Separate subfolders remove
# the collision entirely.
rm -rf docs/schema/v1 docs/schema/v2
poetry run gen-doc --subfolder-type-separation "$V1" -d docs/schema/v1
poetry run gen-doc --subfolder-type-separation "$V2" -d docs/schema/v2

echo "== Render diagrams to full-size SVG =="
# Mermaid rendered client-side inside mkdocs scales itself down to the content
# column, which makes an 11-entity ER diagram unreadable and unzoomable. Rendering
# to SVG ahead of time at natural size (~2600px wide) fixes that: the SVG is
# vector, so it stays crisp at any zoom, and glightbox gives click-to-zoom in the
# site while the raw file opens pannable in any browser.
if [ -n "${MMDC:-}" ]; then
  :                                        # caller-supplied path wins
elif [ -x node_modules/.bin/mmdc ]; then
  MMDC=node_modules/.bin/mmdc              # the reproducible one: npm install
elif command -v mmdc >/dev/null 2>&1; then
  MMDC=mmdc                                # a global install
else
  echo "  mmdc not found -- run 'npm install' in the repo root (see package.json)."
  echo "  Skipping SVG render; pages fall back to inline mermaid."
  MMDC=""
fi

cat > "$OUT/mermaid-config.json" <<'JSON'
{ "theme": "default",
  "er": { "useMaxWidth": false, "entityPadding": 16, "fontSize": 14, "minEntityWidth": 130 },
  "themeVariables": { "fontFamily": "Segoe UI, Helvetica, Arial, sans-serif" } }
JSON

for v in v1 v2; do
  # mmdc wants bare mermaid, not a fenced code block.
  sed '/^```/d' "$OUT/agentjobs-$v.er.mmd" > "$OUT/agentjobs-$v.er.bare.mmd"
  if [ -n "$MMDC" ]; then
    if "$MMDC" -i "$OUT/agentjobs-$v.er.bare.mmd" -o "docs/schema/agentjobs-$v.er.svg" \
               -c "$OUT/mermaid-config.json" -b white --scale 2 >/tmp/mmdc-$v.log 2>&1; then
      echo "  rendered docs/schema/agentjobs-$v.er.svg"
    else
      echo "  WARNING: mmdc failed for $v; page falls back to inline mermaid."
      echo "  If the error mentions a browser, run: npx puppeteer browsers install chromium"
      sed 's/^/    /' /tmp/mmdc-$v.log | tail -5
      rm -f "docs/schema/agentjobs-$v.er.svg"
    fi
  fi
done

echo "== Diagram pages for the site =="
write_erd_page() {
  local v="$1" label="$2" src="$3"
  {
    echo "# Schema $label -- entity diagram"
    echo
    echo "Generated by \`gen-erdiagram\` from \`$src\`, rendered to SVG by \`mmdc\`."
    echo "Do not hand-edit -- run \`scripts/regen-schema-docs.sh\`."
    echo
    if [ -f "docs/schema/agentjobs-$v.er.svg" ]; then
      echo "**[Open the full-size SVG](agentjobs-$v.er.svg)** to pan and zoom natively"
      echo "in your browser. Or click the diagram below to zoom it in place."
      echo
      echo "[![Schema $label entity diagram](agentjobs-$v.er.svg)](agentjobs-$v.er.svg)"
      echo
      echo '??? note "Mermaid source"'
      echo
      sed 's/^/    /' "$OUT/agentjobs-$v.er.mmd"
    else
      cat "$OUT/agentjobs-$v.er.mmd"
    fi
  } > "docs/schema/$v-erd.md"
}
write_erd_page v1 "v1" "$V1"
write_erd_page v2 "v2" "$V2"

echo
echo "== Validate the v2 examples against v2 =="
# These are the teaching artifacts (docs/schema/understanding.md walks through them).
# If a schema change breaks them, the explanation is wrong too -- fail loudly.
for ex in schema/examples/*.yaml; do
  [ -e "$ex" ] || continue
  if poetry run linkml-validate -s "$V2" --target-class Task "$ex" 2>&1 | grep -q "No issues found"; then
    echo "  ok: $ex"
  else
    echo "  FAIL: $ex"
    poetry run linkml-validate -s "$V2" --target-class Task "$ex" 2>&1 | grep ERROR | cut -c1-160 | head -5
    fail_examples=1
  fi
done

echo
# Every task file carries `schema: 2`, so validating them against $V1 reported success
# against a schema none of them claim -- a check that could never have failed. Corrected
# 2026-08-18 as part of task-069, whose sc-4 ("the corpus still validates") was
# meaningless while this loop pointed at v1.
echo "== Validate the live corpus against v2 =="
pass=0
fail=0
for f in tasks/agentjobs/*.yaml tasks/test-data/*.yaml; do
  if poetry run linkml-validate -s "$V2" --target-class Task "$f" 2>&1 | grep -q "No issues found"; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    echo "FAIL: $f"
    poetry run linkml-validate -s "$V2" --target-class Task "$f" 2>&1 | head -5
  fi
done
echo "corpus: $pass passed, $fail failed"

echo
echo "Done. Browse with:  poetry run mkdocs serve"
if [ "$fail" -gt 0 ] || [ -n "${fail_examples:-}" ]; then
  exit 1
fi
